classDiagram
  class Money {
    +MoneyCurrencyEnum currency
    +Number amount
  }
  class Product {
    +String id
    +String name
    +Money price
  }
  class ProductCatalog {
  }
  class MoneyCurrencyEnum {
    USD
    EUR
    GBP
  }
  <<enumeration>> MoneyCurrencyEnum

  Product o-- Money : price
  ProductCatalog "1" --> "*" Product : products
